name: flutter_base
description: FlutterBase

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  easy_localization: ^3.0.1
  retrofit: '>=4.0.0 <5.0.0'
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.0
  logger: any
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.2.1
  flutter_config: ^2.0.0
  bloc: ^8.1.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^6.0.0+1
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/translations/
    - lib/assets/images/
